name: agentic_architecture
description: A production-ready Flutter package for building intelligent agent-based applications with support for single agents, Mixture of Experts (MOE), and pluggable LLM providers.
version: 0.1.0
homepage: https://github.com/Livingstone99/agentic_architecture
repository: https://github.com/Livingstone99/agentic_architecture
issue_tracker: https://github.com/Livingstone99/agentic_architecture/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  test: ^1.24.0

flutter:
  # This package contains Flutter widgets
  uses-material-design: true

